In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
#step 1 : load data
data = pd.read_csv('data_for_neural_net.csv',header=0)

In [3]:
data.columns.values

array(['index', 'area', 'bathrooms', 'price', 'sq_price'], dtype=object)

In [4]:
data.drop(['index', 'price', 'sq_price'],axis = 1,inplace=True)

In [5]:
data = data[:10]

In [6]:
data

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [52]:
data['y1'] = [1,1,1,1,1,0,1,0,0,0]
data['y2'] = data['y1'] == 0
data['y2'] = data.y2.astype('int')

In [53]:
data

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   1   0
4  3000.0        4.0   1   0
5  1985.0        4.0   0   1
6  1534.0        3.0   1   0
7  1427.0        3.0   0   1
8  1380.0        3.0   0   1
9  1494.0        3.0   0   1

In [54]:
#Step 3 - prepare data for Tensorflow(tensors)
#tensors : generic version of scalar, vectors and matrices
#vector: a list of numbers (1D tensor)
#matrices : a list of list of numbers (2D tensor)
#list of list of list of numbers (3D tensor)
#.....and so on
#convert features into input tensors
inputX = data.loc[:,['area','bathrooms']].as_matrix()
#convert labels to tensors
inputY = data.loc[:,['y1','y2']].as_matrix()

In [55]:
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [56]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1]])

In [57]:
#Step 4 - write out our hyperparameters
learning_rate = 0.00000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [58]:
#Step 5 - create Computional Graph
#for feature input tensors, none means any number of examples
#placeholders are gateways for data to our computational graphs
x = tf.placeholder(tf.float32,[None,2]) #since two features
y = tf.placeholder(tf.float32,[None,2]) #since two output classes

#create weights
# 2x2 float matrix that will get updated through the training process
#why Variables?
#variables in tensorflow hold and update parameters in the computational graph
w  = tf.Variable(tf.zeros([2,2]))

#biases
b = tf.Variable(tf.zeros([2]))

#multiply weights with input x
wxplusb = tf.add(tf.matmul(x,w),b)

#softmax activation function
activation = tf.nn.softmax(wxplusb)

In [59]:
#cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(wxplusb,y))
cost = tf.reduce_mean(tf.reduce_sum(tf.square(y-activation),reduction_indices=[1]))
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [60]:
#initialize all variable and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

In [61]:
#training
for i in range(training_epochs):
    sess.run(optimizer,feed_dict={x:inputX,y:inputY})
    if i % display_step == 0:
        cc = sess.run(cost,feed_dict={x:inputX,y:inputY})
        print "training cost : %0.3f" % cc
print("Optimization finished")
print("Final cost : %0.3f" % sess.run(cost,feed_dict={x:inputX,y:inputY}))
print("Weights : ",sess.run(w,feed_dict={x:inputX,y:inputY}))
print("Biases : ",sess.run(b,feed_dict={x:inputX,y:inputY}))

training cost : 0.498
training cost : 0.462
training cost : 0.457
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
training cost : 0.456
Optimization finished
Final cost : 0.456
('Weights : ', array([[  1.54928523e-04,  -1.54928784e-04],
       [ -3.7502311

In [62]:
sess.run(activation,feed_dict={x:inputX})

array([[ 0.65744203,  0.34255797],
       [ 0.62145948,  0.37854049],
       [ 0.67778987,  0.3222101 ],
       [ 0.60795909,  0.39204091],
       [ 0.71698201,  0.28301796],
       [ 0.64908856,  0.35091147],
       [ 0.61663675,  0.38336328],
       [ 0.60876942,  0.39123061],
       [ 0.60529542,  0.39470458],
       [ 0.61370254,  0.3862974 ]], dtype=float32)

In [63]:
sess.run(y,feed_dict={y:inputY})

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]], dtype=float32)

In [64]:
#how to improve the results?
#add hidden layers if not adding more features